module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '../..',
  transform: {
    "^.+\.(ts|tsx|mts|js|jsx)$": ["ts-jest", {
      useESM: true,
      tsconfig: "config/typescript/tsconfig.test.json",
      diagnostics: false
    }]
  },
  transformIgnorePatterns: [
    "node_modules/(?!(?:.pnpm/)?(@web3-storage|@helia)/)"
  ],
  // Add this to ensure Jest processes .mjs files as modules
  "moduleFileExtensions": ["ts", "tsx", "js", "jsx", "json", "node", "mjs"],
  resolver: 'ts-jest-resolver',
  moduleNameMapper: {
    "^uuid$": require.resolve('uuid'),
    "^(merkletreejs)$": "<rootDir>/node_modules/merkletreejs/dist/index.js",
    "^(zod)$": "<rootDir>/node_modules/zod/dist/esm/index.js",
    "../types/ai": "<rootDir>/src/types/ai.ts",
    "../types/common": "<rootDir>/src/types/common.ts",
    "^@src/(.*)$": "<rootDir>/src/$1",
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@test-helpers/(.*)$": "<rootDir>/test/helpers/$1",
    "../utils/test-helpers": "<rootDir>/test/utils/test-helpers.ts",
    "^@web/(.*)$": "<rootDir>/web/$1",
    "^@cli/(.*)$": "<rootDir>/src/cli/$1",
    "^@services/(.*)$": "<rootDir>/src/services/$1",
    "^@storage/(.*)$": "<rootDir>/src/storage/$1",
    "^@utils/(.*)$": "<rootDir>/src/utils/$1",
    "^@ai/(.*)$": "<rootDir>/src/ai/$1",
    "^@tasks/(.*)$": "<rootDir>/src/tasks/$1",
    "^@integrations/(.*)$": "<rootDir>/src/integrations/$1",
    "^@models/(.*)$": "<rootDir>/src/models/$1",
    "^@commands/(.*)$": "<rootDir>/src/commands/$1",
    "^@config/(.*)$": "<rootDir>/src/config/$1",
    "^@auth/(.*)$": "<rootDir>/src/auth/$1",
    "^@api/(.*)$": "<rootDir>/src/api/$1",
    "^@monitoring/(.*)$": "<rootDir>/src/monitoring/$1",
    "^@plugins/(.*)$": "<rootDir>/src/plugins/$1",
    "^@release/(.*)$": "<rootDir>/src/release/$1",
    "^@testing/(.*)$": "<rootDir>/src/testing/$1",
    "^@tasknet/(.*)$": "<rootDir>/src/tasknet/$1",
    "^@ux/(.*)$": "<rootDir>/src/ux/$1",
    "^@workers/(.*)$": "<rootDir>/src/workers/$1",
    "^@vfs/(.*)$": "<rootDir>/src/vfs/$1",
    "^@examples/(.*)$": "<rootDir>/examples/$1",
    "^@screens/(.*)$": "<rootDir>/src/screens/$1",
    "^@components/(.*)$": "<rootDir>/src/components/$1",
    "^@constants/(.*)$": "<rootDir>/src/constants/$1",
    "^@history/(.*)$": "<rootDir>/src/history/$1",
    "^@context/(.*)$": "<rootDir>/src/context/$1",
    "^@permissions/(.*)$": "<rootDir>/src/permissions/$1",
    "^@tools/(.*)$": "<rootDir>/src/tools/$1",
    "^@ipfs/(.*)$": "<rootDir>/src/ipfs/$1",
    "^@patches/(.*)$": "<rootDir>/src/patches/$1",
    "^@types/(.*)$": "<rootDir>/src/types/$1",
    "^@web-components/(.*)$": "<rootDir>/web/src/components/$1",
    "^@web-apps/(.*)$": "<rootDir>/web/src/apps/$1",
    "^@web-adapters/(.*)$": "<rootDir>/web/src/adapters/$1",
    "^@web-state/(.*)$": "<rootDir>/web/src/state/$1",
    "^@web-utils/(.*)$": "<rootDir>/web/src/utils/$1",
    "^@web-screens/(.*)$": "<rootDir>/web/src/screens/$1",
    "^@web-constants/(.*)$": "<rootDir>/web/src/constants/$1",
    "^@web-history/(.*)$": "<rootDir>/web/src/history/$1",
    "^@web-context/(.*)$": "<rootDir>/web/src/context/$1",
    "^@web-permissions/(.*)$": "<rootDir>/web/src/permissions/$1",
    "^@web-tools/(.*)$": "<rootDir>/web/src/tools/$1",
    "^@web-ipfs/(.*)$": "<rootDir>/web/src/ipfs/$1",
    "^@web-patches/(.*)$": "<rootDir>/web/src/patches/$1",
    "^@web-types/(.*)$": "<rootDir>/web/src/types/$1"
  },
  testEnvironmentOptions: {
    customExportConditions: ['node', 'node-addons'],
  },
  globals: {
    'crypto': require('crypto'),
  },
    setupFilesAfterEnv: ['<rootDir>/test/jest.setup.minimal.js'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  modulePaths: ['<rootDir>/src', '<rootDir>/test'],
  testMatch: [
    "<rootDir>/test/**/*.test.ts",
    "<rootDir>/test/**/*.test.tsx",
    "<rootDir>/test/**/*.test.js",
    "<rootDir>/test/**/*.test.jsx",
    "<rootDir>/src/**/*.test.ts",
    "<rootDir>/src/**/*.test.tsx",
    "<rootDir>/src/**/*.test.js",
    "<rootDir>/src/**/*.test.jsx"
  ],
  verbose: true,
  testTimeout: 10000,
  maxWorkers: 1,
  forceExit: true,
  detectOpenHandles: true,
  collectCoverageFrom: [
    "src/**/*.{ts,js}",
    "!src/**/*.d.ts"
  ]
};