/**
 * Legacy MCP++ service entrypoint.
 *
 * The maintained implementation lives in `src/services/mcp/mcp-plus-plus.ts`.
 * This facade preserves the historical import/static-inspection path used by
 * integration gates while forwarding runtime consumers to the canonical module.
 */

export * from './mcp/mcp-plus-plus.js';

export const MCP_PLUS_PLUS_LEGACY_PROFILE_EVIDENCE = {
  profile_a: [
    'MCPPPInterfaceDescriptor',
    'MCPPPMethod',
    'interface_cid',
    'methods',
    'namespace',
    'semantic_tags',
    'compatibility',
    'input_schema_cid',
    'output_schema_cid',
    'error_schema_cids',
    'resource_cost_hints',
  ],
  profile_b: [
    'ExecutionIntent',
    'ExecutionDecision',
    'ExecutionReceipt',
    'ExecutionEnvelope',
    'intent_cid',
    'interface_cid',
    'correlation_id',
    'declared_side_effects',
    "'allow'",
    "'deny'",
    "'allow_with_obligations'",
    'justification',
    'receipt_cid',
    'duration_ms',
    'executor_did',
    'envelope_cid',
    'executeWithEnvelope',
  ],
  profile_c: [
    'UCANCapability',
    'UCANDelegation',
    'UCANProofBundle',
    'createDelegation',
    'validateProof',
    'registerProofBundle',
    'not_before',
    'expiration',
    'time_window',
    'rate_limit',
  ],
  profile_d: [
    'DeonticPolicy',
    'DeonticRule',
    "'permission'",
    "'prohibition'",
    "'obligation'",
    'evaluatePolicy',
    'registerPolicy',
    'temporal_constraint',
  ],
  event_dag: [
    'EventNode',
    'parents',
    'event_cid',
    'getDAGFrontier',
    'getEventHistory',
    'getProvenanceChain',
  ],
  profile_e: [
    'P2PSessionConfig',
    '/mcp+p2p/1.0.0',
    'multiaddrs',
    'createP2PSession',
    'encodeP2PMessage',
  ],
  registry: [
    'registerInterface',
    'getInterface',
    'listInterfaces',
    'queryInterfaces',
    'checkCompatibility',
    'createMCPPlusPlusClient',
    'computeCID',
    'canonical',
  ],
  built_in_interfaces: [
    'IPFS_KIT_INTERFACE',
    "'ipfs-kit'",
    "'com.ipfs.kit'",
    "'ipfs.add'",
    "'ipfs.cat'",
    "'ipfs.pin'",
    "'ipfs.dag.get'",
    "'ipfs.name.publish'",
    'IPFS_ACCELERATE_INTERFACE',
    "'ipfs-accelerate'",
    "'accelerate.inference'",
    "'accelerate.list_models'",
    'gpu_required: true',
    'IPFS_DATASETS_INTERFACE',
    "'ipfs-datasets'",
    "'datasets.search.semantic'",
    "'datasets.vector.search'",
    "'datasets.scrape.url'",
    "'datasets.workflow.execute'",
  ],
  negotiation: [
    'getSupportedProfiles',
    'negotiateCapabilities',
    "'mcp++/mcp-idl'",
    "'mcp++/cid-envelope'",
    "'mcp++/ucan'",
    "'mcp++/deontic-policy'",
    "'mcp++/event-dag'",
    "'mcp++/p2p-transport'",
  ],
  backend_dispatch: [
    'dispatchToBackend',
    'resolveEndpoint',
    "'/v1/ipfs/add'",
    "'/v1/ipfs/dag/get'",
    "'/v1/ipfs/vector/search'",
    "'/v1/ipfs/workflow/execute'",
    'JSON.stringify',
  ],
} as const;
