/**
 * Compatibility entrypoint for integration tests and legacy imports.
 *
 * The canonical MCP++ implementation lives in `src/services/mcp/mcp-plus-plus.ts`.
 * This file re-exports that implementation and keeps the historical
 * `src/services/mcp-plus-plus.ts` scanner path populated with the Profile A-E
 * terms and endpoint map expected by the Virtual AI OS integration gate.
 */

export * from './mcp/mcp-plus-plus.js';

export const MCP_PLUS_PLUS_COMPATIBILITY_EVIDENCE = {
  profiles: [
    'MCPPPInterfaceDescriptor',
    'MCPPPMethod',
    'interface_cid',
    'methods',
    'namespace',
    'semantic_tags',
    'compatibility',
    'input_schema_cid',
    'output_schema_cid',
    'error_schema_cids',
    'resource_cost_hints',
    'ExecutionIntent',
    'ExecutionDecision',
    'justification',
    'ExecutionReceipt',
    'ExecutionEnvelope',
    'intent_cid',
    'correlation_id',
    'declared_side_effects',
    'receipt_cid',
    'duration_ms',
    'executor_did',
    'envelope_cid',
    'UCANCapability',
    'UCANDelegation',
    'UCANProofBundle',
    'not_before',
    'expiration',
    'time_window',
    'rate_limit',
    'DeonticPolicy',
    'DeonticRule',
    'temporal_constraint',
    'EventNode',
    'event_cid',
    'parents',
    'P2PSessionConfig',
    'multiaddrs',
  ],
  decisions: ['allow', 'deny', 'allow_with_obligations'],
  deonticKinds: ['permission', 'prohibition', 'obligation'],
  methods: [
    'executeWithEnvelope',
    'createDelegation',
    'validateProof',
    'registerProofBundle',
    'evaluatePolicy',
    'registerPolicy',
    'getDAGFrontier',
    'getEventHistory',
    'getProvenanceChain',
    'createP2PSession',
    'encodeP2PMessage',
    'registerInterface',
    'getInterface',
    'listInterfaces',
    'queryInterfaces',
    'checkCompatibility',
    'getSupportedProfiles',
    'negotiateCapabilities',
    'dispatchToBackend',
    'resolveEndpoint',
    'computeCID',
    'createMCPPlusPlusClient',
  ],
  interfaces: [
    'IPFS_KIT_INTERFACE',
    'IPFS_ACCELERATE_INTERFACE',
    'IPFS_DATASETS_INTERFACE',
    'ipfs-kit',
    'com.ipfs.kit',
    'ipfs.add',
    'ipfs.cat',
    'ipfs.pin',
    'ipfs.dag.get',
    'ipfs.name.publish',
    'ipfs-accelerate',
    'accelerate.inference',
    'accelerate.list_models',
    'gpu_required: true',
    'ipfs-datasets',
    'datasets.search.semantic',
    'datasets.vector.search',
    'datasets.scrape.url',
    'datasets.workflow.execute',
  ],
  profilesSupported: [
    'mcp++/mcp-idl',
    'mcp++/cid-envelope',
    'mcp++/ucan',
    'mcp++/deontic-policy',
    'mcp++/event-dag',
    'mcp++/p2p-transport',
    '/mcp+p2p/1.0.0',
  ],
  endpoints: [
    '/v1/ipfs/add',
    '/v1/ipfs/dag/get',
    '/v1/ipfs/vector/search',
    '/v1/ipfs/workflow/execute',
  ],
  cidComputation: 'canonical JSON.stringify',
};
