/**
 * SMT2Serializer — translate swissknife deontic Policy formulas to SMT-LIB2.
 *
 * SMT-LIB2 is the common text wire format accepted by both Z3 (`--smt2` mode)
 * and CVC5, enabling a single serializer to feed both SMT prover bridges.
 *
 * Reference: ipfs_datasets_py/logic/external_provers/smt/z3_prover_bridge.py
 *   class TDFOLToZ3Converter — same target semantics, SMT-LIB2 text output.
 *
 * Encoding conventions
 * --------------------
 * - Each permission / prohibition is encoded as a Bool constant `cap__rsc`.
 * - Wildcard `*` in cap or rsc becomes `STAR`.
 * - A permission asserted true + corresponding prohibition asserted true creates
 *   a direct contradiction via `(assert (not (and P_x Prohib_x)))`.
 * - Obligations with a requiredCap that is prohibited encode as another conflict.
 * - `(check-sat)` at the end; `sat` means consistent, `unsat` means conflicting.
 */

import type { Policy } from '../mcp-policy.js';
import type { PolicyFormulaSet } from '../mcp-remote-deontic-engine.js';

// ---------------------------------------------------------------------------
// SMT2Serializer
// ---------------------------------------------------------------------------

export class SMT2Serializer {
  // ---------------------------------------------------------------------------
  // Policy → SMT-LIB2
  // ---------------------------------------------------------------------------

  /**
   * Serialize a MCP++ Profile-D `Policy` to an SMT-LIB2 string.
   *
   * The resulting string can be passed directly to Z3 or CVC5:
   * - `sat`   → policy is consistent (no contradiction detected)
   * - `unsat` → policy is self-contradictory (permission + prohibition on the
   *             same cap+rsc, or obligation whose requiredCap is prohibited)
   */
  policyToSMT2(policy: Policy): string {
    const decls: string[] = [];
    const assertions: string[] = [];

    const permSymbols = new Map<string, string>();
    const prohibSymbols = new Map<string, string>();

    for (const perm of policy.permissions ?? []) {
      const sym = `P__${smtAtom(perm.cap)}__${smtAtom(perm.rsc)}`;
      if (!permSymbols.has(sym)) {
        decls.push(`(declare-const ${sym} Bool)`);
        permSymbols.set(sym, sym);
      }
      assertions.push(`(assert ${sym})`);
    }

    for (const prohib of policy.prohibitions ?? []) {
      const sym = `F__${smtAtom(prohib.cap)}__${smtAtom(prohib.rsc)}`;
      if (!prohibSymbols.has(sym)) {
        decls.push(`(declare-const ${sym} Bool)`);
        prohibSymbols.set(sym, sym);
      }
      assertions.push(`(assert ${sym})`);
    }

    // Conflict: same cap+rsc is both permitted and prohibited → contradiction
    for (const [permSym] of permSymbols) {
      const body = permSym.slice('P__'.length); // cap__rsc
      const prohibSym = `F__${body}`;
      if (prohibSymbols.has(prohibSym)) {
        // Add contradiction: P AND F is unsatisfiable
        assertions.push(`(assert (not (and ${permSym} ${prohibSym})))`);
      }
    }

    // Wildcard permission + any prohibition → conflict
    for (const [permSym] of permSymbols) {
      if (permSym.includes('__STAR__') || permSym.endsWith('__STAR')) {
        for (const [prohibSym] of prohibSymbols) {
          assertions.push(`(assert (not (and ${permSym} ${prohibSym})))`);
        }
      }
    }

    // Obligation with requiredCap that is prohibited
    for (const obl of policy.obligations ?? []) {
      if (!obl.requiredCap) continue;
      const oblCap = smtAtom(obl.requiredCap);
      for (const [prohibSym] of prohibSymbols) {
        if (prohibSym.startsWith(`F__${oblCap}__`) || prohibSym.startsWith('F__STAR__')) {
          const oblSym = `Obl__${oblCap}`;
          if (!decls.some(d => d.includes(oblSym))) {
            decls.push(`(declare-const ${oblSym} Bool)`);
            assertions.push(`(assert ${oblSym})`);
          }
          assertions.push(`(assert (not (and ${oblSym} ${prohibSym})))`);
        }
      }
    }

    const lines = [
      '; Policy consistency check — generated by SMT2Serializer',
      `; Policy: ${policy.id} v${policy.version}`,
      '(set-logic QF_UF)',  // QF_UF for policy-consistency path; use serializeQuantifiedSmt2() for FOL
      ...decls,
      ...assertions,
      '(check-sat)',
    ];
    return lines.join('\n');
  }

  /**
   * Serialize a raw `PolicyFormulaSet` (TDFOL operator strings) to SMT-LIB2.
   *
   * This is a lightweight pass: TDFOL operators `O(cap, rsc)`, `P(cap, rsc)`,
   * `F(cap, rsc)` are encoded as uninterpreted Bool constants and consistency
   * is checked by looking for explicit P+F clashes.
   */
  formulaSetToSMT2(formulaSet: PolicyFormulaSet): string {
    const allFormulas = [
      ...(formulaSet.obligation_formulas ?? []),
      ...(formulaSet.permission_formulas ?? []),
      ...(formulaSet.prohibition_formulas ?? []),
    ];

    const decls: string[] = [];
    const seen = new Set<string>();

    for (const formula of allFormulas) {
      const sym = `formula__${smtAtom(formula)}`.slice(0, 80);
      if (!seen.has(sym)) {
        seen.add(sym);
        decls.push(`(declare-const ${sym} Bool)`);
      }
    }

    // Heuristic: if both P(x) and F(x) appear, add contradiction
    const permFormulas = new Set(formulaSet.permission_formulas ?? []);
    for (const prohib of formulaSet.prohibition_formulas ?? []) {
      const corresponding = prohib.replace(/^F\(/, 'P(');
      if (permFormulas.has(corresponding)) {
        const pSym = `formula__${smtAtom(corresponding)}`.slice(0, 80);
        const fSym = `formula__${smtAtom(prohib)}`.slice(0, 80);
        decls.push(`(assert (not (and ${pSym} ${fSym})))`);
      }
    }

    return [
      '; PolicyFormulaSet consistency check',
      '(set-logic QF_UF)',  // QF_UF for policy-consistency path; use serializeQuantifiedSmt2() for FOL
      ...decls,
      '(check-sat)',
    ].join('\n');
  }

  // ---------------------------------------------------------------------------
  // Parse SMT-LIB2 output
  // ---------------------------------------------------------------------------

  /**
   * Parse the first meaningful line of a Z3/CVC5 SMT-LIB2 response.
   * Returns `'sat'`, `'unsat'`, or `'unknown'`.
   */
  static parseCheckSatResult(output: string): 'sat' | 'unsat' | 'unknown' {
    const first = output.trim().split('\n')[0]?.trim().toLowerCase() ?? '';
    if (first === 'sat') return 'sat';
    if (first === 'unsat') return 'unsat';
    return 'unknown';
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Sanitize a capability/resource string to a valid SMT-LIB2 symbol name. */
function smtAtom(s: string): string {
  if (s === '*') return 'STAR';
  return s.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9_]+/, '').slice(0, 50) || 'any';
}

// PORT-021: Quantifier serialization — ∀/∃ over uninterpreted sorts
export function serializeQuantifiedSmt2(
  quantifier: '∀' | '∃' | 'forall' | 'exists',
  variable:   string,
  sort:       string,
  body:       string,
): string {
  const q = (quantifier === '∀' || quantifier === 'forall') ? 'forall' : 'exists';
  return `(${q} ((${variable} ${sort})) ${body})`;
}

// PORT-021: Uninterpreted function declaration
export function declareFunctionSmt2(name: string, argSorts: string[], returnSort = 'Bool'): string {
  const argStr = argSorts.length > 0 ? argSorts.join(' ') : '';
  return `(declare-fun ${name} (${argStr}) ${returnSort})`;
}

// PORT-022: SMT symbol naming alignment — Python uses DeclareSort+node names,
// TS uses P__cap__rsc style. Align by replacing TS mangling with Python convention.
export function alignSmtSymbolName(tsName: string): string {
  // Convert TS-style mangled names to Python-style sort declarations
  return tsName
    .replace(/__cap__/g, '.')   // P__cap__rsc → P.rsc
    .replace(/__dot__/g, '.')
    .replace(/__slash__/g, '/')
    .replace(/([A-Z])/g, (m) => m.toLowerCase()); // normalize case
}

export function toPythonSmtName(variableName: string, sortName = 'Bool'): string {
  // Python: (declare-const name Bool) style
  return `(declare-const ${variableName} ${sortName})`;
}
