import { createRequire } from 'node:module';
import { describe, expect, it } from 'vitest';
const require = createRequire(import.meta.url);
const { createProfileHAdapter } = require('../../scripts/mcpplusplus-profile-h-adapter.cjs');
const { profileEInitializeResult } = require('../../scripts/mcpplusplus-profile-e-http.cjs');
const methods = ['mcp++/payments/profile','mcp++/payments/catalog','mcp++/payments/quote','mcp++/payments/verify','mcp++/payments/settle','mcp++/payments/receipt/get','mcp++/payments/entitlement/get','mcp++/payments/usage/get','mcp++/payments/refund/request','mcp++/payments/reconcile'];
const profile = { profile: 'mcp++/x402-payments', version: '1.0', ready: true, sellerDid: 'did:web:seller.test', catalogCid: 'baguqcatalog', methods, transports: ['http','libp2p'], mode: 'local-test', upstreamX402HttpConformance: false, durability: { ledger: 'durable', artifactStore: 'content-addressed', reconciliation: true }, facilitator: { ready: true } };
function response(body: unknown, status = 200, headers: Record<string,string> = {}) { return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json', ...headers } }); }
describe('Profile H compatibility adapter', () => {
  it('is typed-unavailable and unadvertisable without a configured seller', async () => { const adapter = createProfileHAdapter({ service: 'ipfs_kit_py', endpoint: '' }); await expect(adapter.isAvailable()).resolves.toBe(false); await expect(adapter.call('mcp++/payments/catalog')).rejects.toMatchObject({ code: -32070 }); });
  it('requires complete durable HTTP/libp2p readiness and honest local-test labeling', async () => { for (const invalid of [{ ...profile, durability: { ...profile.durability, ledger: 'ephemeral' } }, { ...profile, upstreamX402HttpConformance: true }, { ...profile, facilitator: { ready: false } }]) { const adapter = createProfileHAdapter({ endpoint: 'http://seller.test', fetchImpl: async () => response(invalid) }); await expect(adapter.isAvailable()).resolves.toBe(false); } });
  it('advertises only a ready seller that the client explicitly requested', () => { const requested = { capabilities: { experimental: { 'mcp++/x402-payments': true } } }; expect(profileEInitializeResult({ name: 'seller', version: '1', request: requested, supportsX402Payments: true }).capabilities.experimental).toHaveProperty('mcp++/x402-payments', true); expect(profileEInitializeResult({ name: 'seller', version: '1', request: requested, supportsX402Payments: false }).capabilities.experimental).not.toHaveProperty('mcp++/x402-payments'); });
  it('forwards every control method and only payment-safe headers', async () => {
    const calls: Array<{ method: string; path: string; headers: Record<string,string> }> = [];
    const adapter = createProfileHAdapter({ endpoint: 'http://seller.test', fetchImpl: async (url: string, init: RequestInit) => { const path = new URL(url).pathname; calls.push({ method: String(init.method), path, headers: init.headers as Record<string,string> }); if (path === '/mcp/payments/profile') return response(profile); if (path === '/mcp/payments/quote') return response({ quoteCid: 'quote' }, 402, { 'payment-required': 'required' }); return response({ path }); } });
    await adapter.call('mcp++/payments/catalog'); await adapter.call('mcp++/payments/verify', {}); await adapter.call('mcp++/payments/settle', {}); await adapter.call('mcp++/payments/receipt/get', { receipt_cid: 'receipt' }); await adapter.call('mcp++/payments/entitlement/get', { entitlement_cid: 'entitlement' }); await adapter.call('mcp++/payments/usage/get', { usage_cid: 'usage' }); await adapter.call('mcp++/payments/refund/request', {}); await adapter.call('mcp++/payments/reconcile', {});
    const quote = await adapter.handleHttp({ method: 'POST', path: '/mcp/payments/quote', body: {}, headers: { authorization: 'secret', 'payment-signature': 'signed', 'idempotency-key': 'key' } });
    expect(quote).toMatchObject({ status: 402, headers: { 'payment-required': 'required' } }); expect(calls.at(-1)!.headers).not.toHaveProperty('authorization'); expect(calls.map(c => `${c.method} ${c.path}`)).toEqual(expect.arrayContaining(['GET /mcp/payments/catalog','POST /mcp/payments/verify','POST /mcp/payments/settle','GET /mcp/payments/receipts/receipt','GET /mcp/payments/entitlements/entitlement','GET /mcp/payments/usage/usage','POST /mcp/payments/refunds','POST /mcp/payments/reconcile']));
  });
});
