#!/bin/bash

# GitHub Actions Runner Configuration Helper
echo "=== GitHub Actions Runner Configuration ==="
echo ""
echo "The ARM64 runner is now installed at: /opt/actions-runner"
echo ""
echo "To configure the runner, you need to:"
echo ""
echo "1. Go to: https://github.com/endomorphosis/swissknife/settings/actions/runners"
echo "2. Click 'New self-hosted runner'"
echo "3. Select 'Linux' and 'ARM64'"
echo "4. Copy the registration token from the configuration command"
echo ""
echo "5. Then run the configuration command as the actions user:"
echo "   sudo -u actions ./config.sh --url https://github.com/endomorphosis/swissknife \\"
echo "                               --token YOUR_REGISTRATION_TOKEN_HERE \\"
echo "                               --name swissknife-$(hostname)-arm64 \\"
echo "                               --labels self-hosted,linux,arm64,docker,swissknife \\"
echo "                               --work _work \\"
echo "                               --unattended"
echo ""
echo "6. After configuration, install and start as a service:"
echo "   sudo -u actions ./svc.sh install"
echo "   sudo -u actions ./svc.sh start"
echo ""
echo "Current system architecture: $(uname -m)"
echo "Runner directory: /opt/actions-runner"
echo "Runner user: actions"
echo ""
echo "To check runner status after setup:"
echo "   sudo -u actions ./svc.sh status"
echo ""