#!/bin/bash

# Manual GitHub Actions Runner Registration Guide
echo "=== GitHub Actions Runner Manual Setup ==="
echo ""
echo "1. Go to your repository settings:"
echo "   https://github.com/endomorphosis/swissknife/settings/actions/runners"
echo ""
echo "2. Click 'New self-hosted runner'"
echo "3. Select Linux and x64"
echo "4. Follow the download and configure steps shown on GitHub"
echo ""
echo "5. The registration command will look like:"
echo "   ./config.sh --url https://github.com/endomorphosis/swissknife \\"
echo "             --token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \\"
echo "             --name swissknife-$(hostname) \\"
echo "             --labels self-hosted,linux,x64,docker,swissknife"
echo ""
echo "6. After configuration, start the runner as a service:"
echo "   sudo ./svc.sh install"
echo "   sudo ./svc.sh start"
echo ""
echo "Current runner directory: /opt/actions-runner"
echo "Runner user: actions"
echo ""